# production:
#   url: redis://redis.example.com:6379

local: &local
  adapter: any_cable
  url: redis://localhost:6379

development: *local
test: *local
# config/cable.yml
production:
  adapter: any_cable